# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 20:18
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('codigo', models.CharField(max_length=7, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Codigo Invalido', regex='^[A-Z]{2}-[0-9]{4}$')])),
                ('nombre', models.CharField(max_length=60)),
                ('unidadesCredito', models.IntegerField()),
                ('horasTeoria', models.IntegerField()),
                ('horasPractica', models.IntegerField()),
                ('horasLab', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Asignaturas.Departamento')),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='departamento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Asignaturas.Departamento'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='requisitos',
            field=models.ManyToManyField(blank=True, related_name='_asignatura_requisitos_+', to='Asignaturas.Asignatura'),
        ),
    ]
