# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 06:00
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('codigo', models.CharField(max_length=7, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='El código de la asignatura es inválido', regex='^[A-Z]{2}-[0-9]{4}$'), django.core.validators.MaxLengthValidator(7, message='El código de la asignatura debe contener exactamente 7 caracteres'), django.core.validators.MinLengthValidator(7, message='El código de la asignatura debe contener exactamente 7 caracteres')])),
                ('nombre', models.CharField(max_length=60, validators=[django.core.validators.MaxLengthValidator(60, message='El nombre de la asignatura a lo sumo puede contener 60 caracteres'), django.core.validators.MinLengthValidator(1, message='El nombre de la asignatura debe contener al menos un caracter')])),
                ('unidadesCredito', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, message='La asignatura debe contener al menos una unidad de crédito')])),
                ('horasTeoria', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Las horas de teoría no pueden ser negativas')])),
                ('horasPractica', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Las horas de practica no pueden ser negativas')])),
                ('horasLab', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Las horas de laboratorio no pueden ser negativas')])),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(2, message='El código del Departamento debe contener exactamente 2 caracteres'), django.core.validators.MinLengthValidator(2, message='El código del Departamento debe contener exactamente 2 caracteres')])),
                ('nombre', models.CharField(max_length=60, unique=True, validators=[django.core.validators.MaxLengthValidator(60, message='El nombre del Departamento a lo sumo puede contener 60 caracteres'), django.core.validators.MinLengthValidator(1, message='El nombre de la asignatura debe ser mayor a un caracter')])),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Asignaturas.Departamento')),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='departamento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Asignaturas.Departamento'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='requisitos',
            field=models.ManyToManyField(blank=True, to='Asignaturas.Asignatura'),
        ),
    ]
