# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-15 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('nombre', models.CharField(max_length=60, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('codigo', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('unidadesCredito', models.IntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asignaturas.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('nombre', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigo', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('descripcion', models.CharField(max_length=250)),
                ('nroUC_BasicasEspecializacion', models.IntegerField(default=0)),
                ('nroUC_AreasComplementaria', models.IntegerField(default=0)),
                ('nroUC_Seminarios', models.IntegerField(default=0)),
                ('nroUC_TrabajosDirigidos', models.IntegerField(default=0)),
                ('nroUC_TesisDoctoral', models.IntegerField(default=0)),
                ('total_UC_TesisDoctoral', models.IntegerField(default=0)),
                ('nroUC_Basicas', models.IntegerField(default=0)),
                ('nroUC_Areas', models.IntegerField(default=0)),
                ('nroUC_AsigComplementarias', models.IntegerField(default=0)),
                ('nroUC_TrabajoDeGrado', models.IntegerField(default=0)),
                ('total_UC_Maestria', models.IntegerField(default=0)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asignaturas.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='componente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Asignaturas.Componente'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='departamento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Asignaturas.Departamento'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asignaturas.Programa'),
        ),
        migrations.AddField(
            model_name='area',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asignaturas.Programa'),
        ),
        migrations.AddField(
            model_name='abre',
            name='departamento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Asignaturas.Departamento'),
        ),
        migrations.AddField(
            model_name='abre',
            name='materia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Asignaturas.Asignatura'),
        ),
    ]
