# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-19 21:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asignaturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(default='SD-18', max_length=5, validators=[django.core.validators.MaxLengthValidator(5, message='La específicación del trimestre son máximo 5 letras'), django.core.validators.MinLengthValidator(5, message='La específicación del trimestre son mínimo 5 letras')])),
                ('horario', models.CharField(default='', max_length=15, validators=[django.core.validators.MaxLengthValidator(15, message='El campo de horario puede contener hasta 15 letras'), django.core.validators.MinLengthValidator(3, message='El horario debe contener al menos 3 letras')])),
                ('departamento', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Asignaturas.Departamento')),
                ('materia', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Asignaturas.Asignatura')),
                ('profesor', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Asignaturas.Profesor')),
            ],
            options={
                'ordering': ['trimestre'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='ofertafinal',
            unique_together=set([('trimestre', 'profesor', 'materia')]),
        ),
    ]
