# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asignaturas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignatura',
            options={'ordering': ['codigo']},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['codigo']},
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='horasLab',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='horasPractica',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='horasTeoria',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='unidadesCredito',
            field=models.IntegerField(default=0),
        ),
    ]
