# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-15 07:37
# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 05:49
from __future__ import unicode_literals

from django.db import migrations

def insertarDatos(apps, schema_editor):
        
    rol = apps.get_model("Asignaturas", "Rol")
    # Guardamos el rol de Jefe de Departamento
    r = rol(codigo= 1, nombre="Jefe de Departamento")
    r.save()

    

    # Guardamos los departamentos con sus datos
    dptos = apps.get_model("Asignaturas", "Departamento")
    d1 = dptos(codigo="CI", nombre="Departamento de Computación")
    d2 = dptos(codigo="MA", nombre="Departamento de Matemáticas Puras y Aplicadas")
    d1.save()
    d2.save()

    # Insertamos programas
    prog = apps.get_model("Asignaturas", "Programa")
    pr1 = prog(codigo=5200, nombre="Doctorado En Computación", descripcion="Info general", departamento=d1, nroUC_BasicasEspecializacion=28, nroUC_AreasComplementaria=16, nroUC_Seminarios=6, nroUC_TrabajosDirigidos=12, nroUC_TesisDoctoral=24, total_UC_TesisDoctoral=86, nroUC_Basicas=0, nroUC_Areas=0, nroUC_AsigComplementarias=0, nroUC_TrabajoDeGrado=0, total_UC_Maestria=0)
    pr2 = prog(codigo=5201, nombre="Maestría En Ciencias de la Computación", descripcion="Info general", departamento=d1, nroUC_BasicasEspecializacion=0, nroUC_AreasComplementaria=0, nroUC_Seminarios=0, nroUC_TrabajosDirigidos=0, nroUC_TesisDoctoral=0, total_UC_TesisDoctoral=0, nroUC_Basicas=12, nroUC_Areas=12, nroUC_AsigComplementarias=8, nroUC_TrabajoDeGrado=12, total_UC_Maestria=46)
    pr1.save()
    pr2.save()

    # Area de cada Materia
    area = apps.get_model("Asignaturas", "Area")
    ar1 = area(nombre = "Bases de Datos", programa=pr1)
    ar2 = area(nombre = "Asignaturas Básicas", programa=pr1)
    ar3 = area(nombre = "Inteligencia Artificial", programa=pr1)
    ar4 = area(nombre = "Computación Gráfica y Multimedios", programa=pr1)
    ar5 = area(nombre = "Sistemas Paralelos y Distribuidos", programa=pr1)
    
    ar6 = area(nombre = "Bases de Datos", programa=pr2)
    ar7 = area(nombre = "Asignaturas Básicas", programa=pr2)
    ar8 = area(nombre = "Inteligencia Artificial", programa=pr2)
    ar9 = area(nombre = "Computación Gráfica y Multimedios", programa=pr2)
    ar10 = area(nombre = "Sistemas Paralelos y Distribuidos", programa=pr2)

    ar1.save()
    ar2.save()
    ar3.save()
    ar4.save()
    ar5.save()
    ar6.save()
    ar7.save()
    ar8.save()
    ar9.save()
    ar10.save()

    #Agregamos los componentes que luego se van a relacionar con los programas y las materias
    componente = apps.get_model("Asignaturas","Componente")
    comp1=componente(nombre="Asignaturas Básicas", descripcion="Descripción")
    comp2=componente(nombre="Asignaturas Area de Especialización", descripcion="Descripción")
    comp3=componente(nombre="Asignaturas Areas áfines o Complementarias", descripcion="Descripción")
    comp4=componente(nombre="Asignaturas Seminarios", descripcion="Descripción")
    comp5=componente(nombre="Básicas", descripcion="Descripción")
    comp6=componente(nombre="Area", descripcion="Descripción")
    comp7=componente(nombre="Complementarias", descripcion="Descripción")
    comp8=componente(nombre="Trabajo de Grado", descripcion="Descripción")
    comp1.save()
    comp2.save()
    comp3.save()
    comp4.save()
    comp5.save()
    comp6.save()
    comp7.save()
    comp8.save()


    # Agregamos Asignaturas

    #Maestria Computacion
    asignatura = apps.get_model("Asignaturas","Asignatura")
    asig1 = asignatura(codigo="CI-7311",nombre="Web Semántica", unidadesCredito=4, area=ar1,departamento=d1,componente=comp6,programa=pr2)
    asig2 = asignatura(codigo="CI-7312",nombre="Web Semántica II", unidadesCredito=4, area=ar1,departamento=d1,componente=comp6,programa=pr2)
    asig3 = asignatura(codigo="CI-7431",nombre="Base de Datos Lógicos", unidadesCredito=4, area=ar1,departamento=d1,componente=comp6,programa=pr2)
    asig4 = asignatura(codigo="CI-7432",nombre="Base de Datos Lógicos II", unidadesCredito=4, area=ar1,departamento=d1,componente=comp6,programa=pr2)
    asig5 = asignatura(codigo="CI-5311",nombre="Paradigma en modelaje de Bases de Datos", unidadesCredito=4, area=ar1,departamento=d1,componente=comp6,programa=pr2)
    asig6 = asignatura(codigo="CI-5321",nombre="Computación Gráfica", unidadesCredito=4, area=ar4,departamento=d1,componente=comp6,programa=pr2)
    asig7 = asignatura(codigo="CI-5322",nombre="Computación Gráfica II", unidadesCredito=4, area=ar4,departamento=d1,componente=comp6,programa=pr2)
    asig8 = asignatura(codigo="CI-6352",nombre="Seguridad de Datos", unidadesCredito=4, area=ar5,departamento=d1,componente=comp6,programa=pr2)
    asig9 = asignatura(codigo="CI-7621",nombre="Teoría de Algoritmos", unidadesCredito=4, area=ar2,departamento=d1,componente=comp5,programa=pr2)
    asig10 = asignatura(codigo="CI-7541",nombre="Teoría de la Computación", unidadesCredito=4, area=ar2,departamento=d1,componente=comp5,programa=pr2)
    asig11 = asignatura(codigo="CI-7521",nombre="Matemáticas de Computación", unidadesCredito=4, area=ar2,departamento=d1,componente=comp5,programa=pr2)
    asig12 = asignatura(codigo="CI-5431",nombre="Inteligencia Artificial", unidadesCredito=4, area=ar3,departamento=d1,componente=comp6,programa=pr2)
    asig13 = asignatura(codigo="CI-5432",nombre="Inteligencia Artificial II", unidadesCredito=4, area=ar3,departamento=d1,componente=comp6,programa=pr2)
    asig14 = asignatura(codigo="CI-6432",nombre="Inteligencia Artificial", unidadesCredito=4, area=ar3,departamento=d1,componente=comp6,programa=pr2)
    asig15 = asignatura(codigo="CI-6461",nombre="Inteligencia Artificial II", unidadesCredito=4, area=ar3,departamento=d1,componente=comp6,programa=pr2)
    asig16 = asignatura(codigo="CI-6438",nombre="Programación en Inteligencia Artificial", unidadesCredito=4, area=ar3,departamento=d1,componente=comp6,programa=pr2)
    asig17 = asignatura(codigo="CI-6621",nombre="Algoritmos Paralelos", unidadesCredito=4, area=ar5,departamento=d1,componente=comp6,programa=pr2)

    # Doctorado
    asig18 = asignatura(codigo="CI-7311",nombre="Web Semántica", unidadesCredito=4, area=ar1,departamento=d1,componente=comp2,programa=pr1)
    asig19 = asignatura(codigo="CI-7312",nombre="Web Semántica II", unidadesCredito=4, area=ar1,departamento=d1,componente=comp2,programa=pr1)
    asig20 = asignatura(codigo="CI-7431",nombre="Base de Datos Lógicos", unidadesCredito=4, area=ar1,departamento=d1,componente=comp2,programa=pr1)
    asig21 = asignatura(codigo="CI-7432",nombre="Base de Datos Lógicos II", unidadesCredito=4, area=ar1,departamento=d1,componente=comp2,programa=pr1)
    asig22 = asignatura(codigo="CI-6432",nombre="Inteligencia Artificial", unidadesCredito=4, area=ar3,departamento=d1,componente=comp2,programa=pr1)
    asig23 = asignatura(codigo="CI-6352",nombre="Seguridad de Datos", unidadesCredito=4, area=ar5,departamento=d1,componente=comp2,programa=pr1)

    asig1.save()
    asig2.save()
    asig3.save()
    asig4.save()
    asig5.save()
    asig6.save()
    asig7.save()
    asig8.save()
    asig9.save()
    asig10.save()
    asig11.save()
    asig12.save()
    asig13.save()
    asig14.save()
    asig15.save()
    asig16.save()
    asig17.save()
    asig18.save()
    asig19.save()
    asig20.save()
    asig21.save()
    asig22.save()
    asig23.save()

    abre = apps.get_model("Asignaturas","Abre")

    ab1 = abre(departamento=d1, materia=asig1, trimestre="Septiembre-Diciembre 2018" )
    ab2 = abre(departamento=d1, materia=asig2, trimestre="Septiembre-Diciembre 2018" )
    ab3 = abre(departamento=d1, materia=asig3, trimestre="Septiembre-Diciembre 2018" )
    ab4 = abre(departamento=d1, materia=asig4, trimestre="Septiembre-Diciembre 2018" )
    ab5 = abre(departamento=d1, materia=asig6, trimestre="Septiembre-Diciembre 2018" )
    ab6 = abre(departamento=d1, materia=asig7, trimestre="Septiembre-Diciembre 2018" )

    ab7 = abre(departamento=d1, materia=asig12, trimestre="Enero-Marzo 2019")
    ab8 = abre(departamento=d1, materia=asig13, trimestre="Enero-Marzo 2019")
    ab9 = abre(departamento=d1, materia=asig14, trimestre="Enero-Marzo 2019")
    ab10 = abre(departamento=d1, materia=asig15, trimestre="Enero-Marzo 2019")
    ab11 = abre(departamento=d1, materia=asig11, trimestre="Enero-Marzo 2019")
    ab12 = abre(departamento=d1, materia=asig10, trimestre="Enero-Marzo 2019")

    ab1.save()
    ab2.save()
    ab3.save()
    ab4.save()
    ab5.save()
    ab6.save()
    ab7.save()
    ab8.save()
    ab9.save()
    ab10.save()
    ab11.save()
    ab12.save()

    
class Migration(migrations.Migration):

    dependencies = [
        ('Asignaturas', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insertarDatos),
]
