# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-05 07:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asignaturas', '0002_auto_20181203_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(default='SD-18', max_length=5, validators=[django.core.validators.MaxLengthValidator(5, message='La específicación del trimestre son máximo 5 letras'), django.core.validators.MinLengthValidator(5, message='La específicación del trimestre son mínimo 5 letras')])),
                ('preferencia', models.NullBooleanField(default=None)),
                ('materia', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Asignaturas.Asignatura')),
                ('profesor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Asignaturas.Profesor')),
            ],
            options={
                'ordering': ['trimestre'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='oferta',
            unique_together=set([('trimestre', 'profesor', 'materia')]),
        ),
    ]
