# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-05 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asignaturas', '0003_auto_20181205_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='departamento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Asignaturas.Departamento'),
        ),
    ]
